# Generated by Django 3.1.3 on 2020-11-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
